chore: force the SpiderMonkey build system not to verify the macOS SDK version
The latest version of SpiderMonkey on macOS requires at least Xcode SDK 14.4, but none is available on Github Actions runner's macOS 13 image.
See https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#installed-sdks

ERROR: SDK version "13.3" is too old. Please upgrade to at least 14.4. Try updating your system Xcode.